_wandb:
    value:
        cli_version: 0.25.0
        e:
            9kwcoqch5dri260708tbahivr1roludf:
                codePath: unsloth_ft/models/qwen_3_5_4B_vision/main.py
                codePathLocal: models/qwen_3_5_4B_vision/main.py
                cpu_count: 11
                cpu_count_logical: 22
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "1081101176832"
                        used: "114644054016"
                email: shawon13@live.com
                executable: /home/shawon/Projects/fine-tuning/unsloth_ft/.venv/bin/python3
                git:
                    commit: c76282e63a53cea9b972781fa0667c314bc0252f
                    remote: ssh://codeberg.org/rashomon/fine-tuning.git
                gpu: NVIDIA GeForce RTX 4070 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4070 Laptop GPU
                      uuid: GPU-dd612843-a42f-145e-749e-1bd36cae9a64
                host: blackbeard
                memory:
                    total: "16473817088"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/shawon/Projects/fine-tuning/unsloth_ft/models/qwen_3_5_4B_vision/main.py
                python: CPython 3.12.12
                root: /home/shawon/Projects/fine-tuning/unsloth_ft
                startedAt: "2026-03-10T16:05:10.485099Z"
                writerId: 9kwcoqch5dri260708tbahivr1roludf
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 75
                - 84
                - 98
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 75
                - 84
                - 98
            "3":
                - 13
                - 16
            "4": 3.12.12
            "5": 0.25.0
            "6": 5.2.0
            "12": 0.25.0
            "13": linux-x86_64
dataset_name:
    value: unsloth/LaTeX_OCR
model_name:
    value: unsloth/Qwen3.5-4B
peft_parameters:
    value:
        bias: none
        loftq_config: null
        lora_alpha: 16
        lora_dropout: 0
        r: 16
        random_state: 3407
        target_modules: all-linear
        use_rslora: false
training_parameters:
    value:
        gradient_accumulation_steps: 4
        learning_rate: 0.0002
        logging_steps: 1
        lr_scheduler_type: linear
        num_train_epochs: 50
        optim: adamw_8bit
        per_device_train_batch_size: 8
        warmup_steps: 5
        weight_decay: 0.001
